### PR TITLE
Added footer from the component library

### PR DESCRIPTION
**Pull request by alex-solo**
### Description

The "upArrow" image will not appear until the following PR in the Design System is merged: https://github.com/DTS-STN/DECD-Design-System/pull/235

List of proposed changes:

-
-

### CODE REVIEW

**Comment by alex-solo** [comment]
The design system PR that this PR depends on has been approved and merged.

**Review by MarcoGoC — DISMISSED** [review]
we should add the links, and probably have them on the translation file 
btnLink should point to the H1 of the page

**Comment by JeremyKennedy** [comment]
Definitely not a bad idea to add actual links. It could be a separate PR at a later time, up to you. But for an idea of how we've previously handled links that need to be translated, check out the backend translation file. We have a bunch of links defined there.

**Review by JeremyKennedy — APPROVED** [review]
Definitely not a bad idea to add actual links. It could be a separate PR at a later time, up to you. But for an idea of how we've previously handled links that need to be translated, check out the backend translation file. We have a bunch of links defined there.

**Pull request merged**
