### PR TITLE
Update CustomCollapse.tsx

### PR DESCRIPTION
**Pull request by alexunique0519**
### Description
Added space between the arrow and the heading text, also between the arrow and the vertical line. 

screenshot from Firefox 
Screen Shot 2022-07-26 at 4 23 01 PM

### CODE REVIEW

**Review by MarcoGoC — CHANGES_REQUESTED** [review]
image

the changes create a break in the underline see image (firefox)
and not a lot more space added

**Review by MarcoGoC — CHANGES_REQUESTED** [review]
still looks the same on Firefox
image

I think this looks better 
image

**Comment by alexunique0519** [comment]
> image
> 
> the changes create a break in the underline see image (firefox) and not a lot more space added

**Review by MarcoGoC — APPROVED** [review]
not sure why the branch was not working just did another pull and I got the correct code.

**Pull request merged**
