### PR TITLE
Switched h1 to Heading component

### PR DESCRIPTION
**Pull request by alex-solo**
### Description

List of proposed changes:

-
-

### Additional Notes

Working on a fix to design system to fix h1 underline issue.

### CODE REVIEW

**Comment by alex-solo** [comment]
The 2 PRs for the design system that would make this look the right way are here: 

https://github.com/DTS-STN/DECD-Design-System/pull/240
https://github.com/DTS-STN/DECD-Design-System/pull/239

**Comment by alex-solo** [comment]
The design system PRs that this PR depends on have been approved and merged.

**Review by MarcoGoC — APPROVED** [review]
+1

**Review by alexunique0519 — APPROVED** [review]

**Review by JeremyKennedy — APPROVED** [review]
Looks good! I just updated the id to `applicationTitle` to better reflect the content.

**Pull request merged**
