### PR TITLE
updated currencyField and Income Text

### PR DESCRIPTION
**Pull request by MarcoGoC**
### Description

Update Questions page: Income and add icon with "textbox" 

### What to test for/How to test

- Income text must be the new one. 
- click on the info icon to display the extra

### CODE REVIEW

**Review by alexunique0519 — DISMISSED** [review]
Everything looks good except small style difference in the tooltip text format. For example, "You can find..." and "For a more accurate" should have a space/margin in between. Also, there is no indentation for the bullets.

**Comment by alex-solo** [comment]
Screen Shot 2022-11-02 at 11 30 30 AM

There is also this weird ::after element that is clickable which shouldn't be there

**Review by alex-solo — DISMISSED** [review]
See comment

**Comment by MarcoGoC** [comment]
> Everything looks good except small style difference in the tooltip text format. For example, "You can find..." and "For a more accurate" should have a space/margin in between. Also, there is no indentation for the bullets.

updated

**Comment by MarcoGoC** [comment]
> Screen Shot 2022-11-02 at 11 30 30 AM
> 
> There is also this weird ::after element that is clickable which shouldn't be there

updated, tailwind sometimes takes css from the DS and sometimes does not it's a pain

**Comment by alexunique0519** [comment]
Screen Shot 2022-11-03 at 2 13 09 PM
I think the text area should stay under the icon, it currently breaks the mobile view.

**Pull request closed without merging**
