### PR TITLE
ADO-129804: Duration component; fix ageDate so the year is not undefined

### PR DESCRIPTION
**Pull request by alex-solo**
### Description

- The problem was in the year being "undefined" when the component re-renders 

During refactor, we should save both "age" as well as month and year input instead of calculating month and year from age. This should do for now.

### CODE REVIEW

**Review by MarcoGoC — DISMISSED** [review]
still does not work, issue is not the undefined when rendering but not calling the onChange based on age change or receiving.

**Comment by alex-solo** [comment]
> still does not work, issue is not the undefined when rendering but not calling the onChange based on age change or receiving.

console log the "ageDate" prop - we were getting "undefined" on the birth year. I missed the other scenarios when changing birth month/year so I will address those as well but this addresses the undefined issue

**Review by alex-solo — COMMENTED** [review]
Has been tested by Justin, it's working now

**Review by MarcoGoC — APPROVED** [review]
works now

**Pull request merged**
