### PR TITLE
Update Tailwind to 3

### PR DESCRIPTION
**Pull request by JeremyKennedy**
This is the only major version update we are behind on. Unfortunately it does break some things:
- [x] tooltip icon is invisible
- [x] in tooltip, tooltip icon in header is inverted

### CODE REVIEW

**Comment by JeremyKennedy** [comment]
We have more important things to do than fixing a dependency update, but this would be really nice to get done, as it is the only major version we are behind.

**Comment by KhalidAdan** [comment]
This one gives me the hereby jeebies

**Review by alex-solo — APPROVED** [review]
Met with Khalid who approves these changes

**Comment by JeremyKennedy** [comment]
Hey Alex - looks great! One thing I noticed is that the tooltip icon is now black: 
image
it should be more of a blue: 
image

Inspecting element was a bit weird, it seemed like changing the color via the browser didn't actually affect the tooltip at all. Not sure exactly what is causing this.

**Comment by JeremyKennedy** [comment]
Looks good, thanks!

**Pull request merged**
