### PR TITLE
Added Aria-Label for Required suffix for screen readers to skip the P…

### PR DESCRIPTION
**Pull request by Maxim-Lam**
…arenthesis

### Description

Added Aria-label to "(Required)" suffix for screen readers to ignore the Left and right "paren"

### What to test for/How to test
Either select element with Screen reader or inspect element to see aria-label was added

### CODE REVIEW

**Review by MarcoGoC — COMMENTED** [review]
by following example #4 of this page 
https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html 
the required should be inside the `label` tag. and adding a `aria-required="true"` to the control. 

also according to this page https://a11y-101.com/development/required section `The word` 
`(required)` should be inside the label. 

I am guessing that is the reason why the screen reader is reading left paren - right paren

**Review by MarcoGoC — CHANGES_REQUESTED** [review]
see comment

**Comment by Maxim-Lam** [comment]
> Yes, I believe it should be <span> can help with the styling

I can certainly make those changes.

My only concern was that the Design System Component we are using for the date has the label text and required text in separate paragraphs and therefore separate styles. Adding the required text into the label with give it the same styles and make it less distinguishable.

@MarcoGoC That being said, do you recommend I still just add it as part of the label?

**Comment by alexunique0519** [comment]
Close this PR since another PR for this fix has been merged.

**Pull request closed without merging**
